config/routes.rb
Railshero::Application.routes.draw do
  
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/faq', to: 'static_pages#faq'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Rails Hero"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railshero.com/">Rails Hero</a>
    by Nelson Wittwer
  </small>
  <nav>
    <ul>
      <li><%= link_to "about",   about_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <li><%= link_to "contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navibar">
        <div class="container">
          <%= link_to image_tag("logo.png"), root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-left">
              <li><%= link_to "beginners",    '#' %></li>
              <li><%= link_to "library",    '#' %></li>
              <li><%= link_to "sign in", '#' %></li>
              <li><%= link_to "search              ", '#' %></li>
            </ul>
          </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/FAQ.html.erb
<% provide(:title, 'FAQ') %>
<h1>StaticPages#FAQ</h1>
<p>Find me in app/views/static_pages/FAQ.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="row">
    		<div id="landingHeader" class="span12">
    			<div class="row">
    				<div id="logoMobileNew" class="span6 visible-phone"><%= image_tag("mobilelogo.png", alt: "Rails Hero Logo")%></div>
    				<div class="hidden-phone hidden-tablet"><div id="moon" class="span3"><%= image_tag("moon.png") %></div></div>
    			</div>
    			
    			<div class="row">
    				<div id="callout" class="span6 offset5">
    					
    					<div class="row">
	    					<div class="span5">
	    						<h1>Learn Rails<br> For Free</h1>
	    						<p>Our community gathers the web&#39;s best <strong>free</strong> Rails educational resources and shares them with you. </p>
	    						<div id="newJoin" class="btn-large btn-warning" type="button" value="Join Now!"><h3>Join the Community<h3><p>100% free. Always and Forever.</p></div>
	    					</div> 
	    					
    					</div>
    					
    				</div>
    			</div>
    			
    			
    			<div class="row">
    				<div class="hidden-phone">
    					<div id="skyline" class="span12"> <%= image_tag("heroskyline.png") %></div>
    				</div>
    			</div>
    		</div>
    	</div>
    	
    	<div id="howHome" class="span12">
    			<div class="row">
    				<div class="how span3">
    					<h3>How does it work?</h3>
    				</div>
    				
    				<div class="howWork span9" >
    					<div class="work row">
    						<h3>Community Currated Content</h3>
    						<%= image_tag("curated.png") %>
    						<p>Our community has identified the best free learning material on the web for getting started with Rails. We have gathered it all under one roof to save you time, heartache, and even lowered your blood pressure. Aren&#39;t we nice?</p>
    					</div>
    					
    					<div class="row">
    						<h3>Rails for Beginners</h3>
    						<%= image_tag("beginner.png") %>
    						<p>All of the material we have gathered is geared towards beginners. We do solemly swear that we will not destroy your brain with codez that will break your brain. We are all new at this.</p>
    					</div>
    					
    					<div class="row">
    						<h3>Become a Contributor</h3>
    						<%= image_tag("give.png") %>
    						<p>If you have spot any material on the web that you feel would be a good resource for our community, share what you find! You will be thanked with pictures of dancing cats.</p>
    					</div>
    					
    				</div>
    			</div>
    	</div>